export const videoArray = [
  {name: "Abdominal Crunch", video: "https://assets.codepen.io/1240556/abdominal_crunch.gif"},
  {name: "Air Squat Bent Arms", video: "https://assets.codepen.io/1240556/air_squat_bent_arms.gif"},
  {name: "Bicycle Crunch", video: "https://assets.codepen.io/1240556/bicycle_crunch.gif"},
  {name: "Box Jump", video: "https://assets.codepen.io/1240556/box_jump.gif"},
  {name: "Burpee", video: "https://assets.codepen.io/1240556/burpee.gif"},
  {name: "Circle Crunch", video: "https://assets.codepen.io/1240556/circle_crunch.gif"},
  {name: "Cross Jump", video: "https://assets.codepen.io/1240556/cross_jump.gif"},
  {name: "Cross Jump Rotation", video: "https://assets.codepen.io/1240556/cross_jump_rotation.gif"},
  {name: "Donkey Kick", video: "https://assets.codepen.io/1240556/donkey_kick.gif"},
  {name: "High Knees", video: "https://assets.codepen.io/1240556/high_knees.gif"},
  {name: "Jump Push Ups", video: "https://assets.codepen.io/1240556/jump_push_ups.gif"},
  {name: "Jumping Jack", video: "https://assets.codepen.io/1240556/jumping_jack.gif"},
  {name: "Lunge", video: "https://assets.codepen.io/1240556/lunge.gif"},
  {name: "Lunge Kick", video: "https://assets.codepen.io/1240556/lunge_kick.gif"},
  {name: "Mountain Climbers", video: "https://assets.codepen.io/1240556/mountain_climbers.gif"},
  {name: "Pike Walk", video: "https://assets.codepen.io/1240556/pike_walk.gif"}, 
  {name: "Plank", video: "https://assets.codepen.io/1240556/plank.gif"},
  {name: "Push Up Rotation", video: "https://assets.codepen.io/1240556/push_up_rotation.gif"},
  {name: "Push Ups", video: "https://assets.codepen.io/1240556/push_ups.gif"},
  {name: "Quick Steps", video: "https://assets.codepen.io/1240556/quick_steps.gif"},
  {name: "Russian Twist", video: "https://assets.codepen.io/1240556/russian_twist.gif"},
  {name: "Side Plank", video: "https://assets.codepen.io/1240556/side_plank.gif"},
  {name: "Squat", video: "https://assets.codepen.io/1240556/squat.gif"},
  {name: "Step Up", video: "https://assets.codepen.io/1240556/step_up.gif"},
  {name: "Tricep Dips", video: "https://assets.codepen.io/1240556/tricep_dips.gif"},
  {name: "Victory", video: "https://assets.codepen.io/1240556/victory_1.gif"}, 
  {name: "Wall Sit", video: "https://assets.codepen.io/1240556/wall_sit.gif"}
]