export const videoArray = [
  {name: "Abdominal Crunch", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Air Squad Bent Arms", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Bicycle Crunch", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Box Jump", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Burpee", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Circle Crunch", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Cross Jump", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Cross Jump Rotation", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Donkey Kick", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "High Knees", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Idle", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Jump Push Ups", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Jumping Jack", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Lunge", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Lunge Kick", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Mountain Climbers", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Pike Walk", video: "https://assets.codepen.io/1240556/victory.gif"}, 
  {name: "Plank", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Push Up Rotation", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Push Ups", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Quick Steps", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Russian Twist", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Side Plank", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Squad", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Step Up", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Tricep Dips", video: "https://assets.codepen.io/1240556/victory.gif"},
  {name: "Victory", video: "https://assets.codepen.io/1240556/victory.gif"}, 
  {name: "Wall Sit", video: "https://assets.codepen.io/1240556/victory.gif"}
]